name: AutoBoat Development Container CI

on:
  push:
    branches: ["devcontainer_testing"]
    paths:
      - ".devcontainer/devcontainer_variants/**"
      - ".devcontainer/Dockerfile"
      - ".devcontainer/required_pip_packages.txt"
      - ".github/workflows/devcontainer.yml"
  pull_request:
    branches: ["main"]
    paths:
      - ".devcontainer/devcontainer_variants/**"
      - ".devcontainer/Dockerfile"
      - ".devcontainer/required_pip_packages.txt"
      - ".github/workflows/devcontainer.yml"

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:latest
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push base
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            vtautoboat/autoboat_docker_dev_image:latest
            vtautoboat/autoboat_docker_dev_image:${{ github.sha }}
          cache-from: |
            type=registry,ref=vtautoboat/autoboat_docker_dev_image:cache
          cache-to: |
            type=registry,ref=vtautoboat/autoboat_docker_dev_image:cache,mode=max

  yolo:
    needs: base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:latest
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push yolo
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/devcontainer_variants/Dockerfile.yolo
          platforms: linux/amd64
          push: true
          tags: |
            vtautoboat/autoboat_docker_dev_image:yolo
            vtautoboat/autoboat_docker_dev_image:yolo_${{ github.sha }}
          cache-from: |
            type=registry,ref=vtautoboat/autoboat_docker_dev_image:yolo_cache
          cache-to: |
            type=registry,ref=vtautoboat/autoboat_docker_dev_image:yolo_cache,mode=max
