name: Docker Image CI

on:
  push:
    branches: ["main"]
    # Only trigger when Dockerfile changes
    paths:
      - ".devcontainer/Dockerfile"
  pull_request:
    branches: ["main"]
    paths:
      - ".devcontainer/Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          IMAGE_TAG=vtautoboat/autoboat_docker_dev_image:${{ github.sha }}
          docker build -t $IMAGE_TAG -f .devcontainer/Dockerfile .devcontainer
          docker tag $IMAGE_TAG vtautoboat/autoboat_docker_dev_image:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push vtautoboat/autoboat_docker_dev_image:${{ github.sha }}
          docker push vtautoboat/autoboat_docker_dev_image:latest
